### ISSUE TITLE
Scoring for 5x-7x combos is probably incorrect.

### ISSUE THREAD

**Issue by gary-z** [gary-z/blokie#1]
I did not have any datapoints. If anyone happens to know, especially if you can link a video please let me know.

**Comment by hubbergit** [comment]
![Screenshot_20230501-194020_Blockudoku](https://user-images.githubusercontent.com/132500127/236022985-78741014-8a0e-46c9-b4f7-1b7ed8aad0ad.jpg)
![Screenshot_20230501-220858_Blockudoku](https://user-images.githubusercontent.com/132500127/236023013-2f845807-c849-4e20-bac2-a07d05c581f9.jpg)
![Screenshot_20230501-221008_Blockudoku](https://user-images.githubusercontent.com/132500127/236023049-d844e504-daf7-4eea-aece-fc8ef0842d3f.jpg)

Figured out the scores for 5x and 6x combos. So far they all match 18 multiplied by this sequence: https://oeis.org/A093005 but I'm not sure about 7 and 9.

**Comment by gary-z** [comment]
Thank you! Updated the scoring. 7x and 9x are rare enough that noone will notice if they are incorrect.
