### ISSUE TITLE
Score calculation seems incorrect

### ISSUE THREAD

**Issue by pmurman** [gary-z/blokie#5]
Hi @gary-z,

Great engine!

I ran into two issues using blokie.js:

1) Blokie returns `new_game_states[2]` with `previous_move_was_clear` set, also when there was no clear.
Trivial fix - line 840: `...count(p1);` --> `...count(p2);`

2) The` score_after_p2` does not reflect the correct # points for `placement_p2` when there was a row/col/cube clear.
 When doing the same moves 'manually' using `blokie.get_move_score` & `blokie.perform_clears`, the score is correct.
Would be great if this one could be fixed.

Thanks,
PeterM

**Comment by gary-z** [comment]
Great catch! I think they should be both fixed in [cc585707ec8379453b40fc89f62d2eaf8641ed96](https://github.com/gary-z/blokie/commit/cc585707ec8379453b40fc89f62d2eaf8641ed96).

**Comment by gary-z** [comment]
Could you show me a repro either in code or with a series of screen shots to demonstrate #2?

**Comment by pmurman** [comment]
[blokie_examples.pdf](https://github.com/gary-z/blokie/files/13666169/blokie_examples.pdf)
Hope this helps.

**Comment by gary-z** [comment]
That simple clear on page 4 is worth 18 points + 2 the new uncleared blocks placed on the board.

So 7 + 18 + 2 = 27.

If you try a few examples in the original mobile game I think it matches. 

How did you calculate 29?

**Comment by pmurman** [comment]
So what I did is let blokie produce its best moves for a given piece-set and feed the same placements just to the clear and score methods. That gave me 29, which I think is also correct: after the 7, the next move is 4 which makes 11, and then a clear worth 18 is done = 29.

**Comment by gary-z** [comment]
> after the 7, the next move is 4 which makes 11, and then a clear worth 18 is done = 29.

I think you misunderstood the scoring algorithm. When placing a piece, parts of the piece that are immediately cleared are not counted for scoring. In the example on page 4,  half of the 4 block piece is immediately cleared, so only the two blocks that remain count for 2 points.

In other words, the procedure is not Place -> Score Placement -> Clear -> Score the Clear, but rather Place -> Score Placement and Clears.

I think when you called the score function you may have inputted the incorrect values into the previous state arguments.

**Comment by pmurman** [comment]
You're right - I wasn't aware of this rule!
I haven't found clear scoring rules for the game on the web.
Thanks for helping out - I change my app per your suggestions.

**Comment by gary-z** [comment]
I'd be excited to see what you build :) !

**Comment by pmurman** [comment]
Winter-project on our farmhouse to keep my old brains busy :)
Not sure I will succeed, but if so you will get to see it.

I just had a look at 4 different 'SudoBlock' games, and while each has it own combo/streak bonus rules, they all do:

1. Reward every piece-part being placed
2. Then add bonus award for combo/streak

To me, it also feels more intuitive this way: as a user, I would expect to receive the points for each piece placed, regardless of whether it leads to a clear or not.
No idea how difficult it will be for me to change blokie (any hints would be welcome!). I'd prefer to use blokie instead of doing my own engine (had this originally in mind but that would keep me busy 3 more winters I guess... ;) )

**Comment by gary-z** [comment]
If you want to use blokie but do your own scoring you've a couple options.
- Ignore blokie's scoring and write your own scoring function. The down side here is if you decide to use the AI part of blokie it will make slightly suboptimal moves.
- Edit the scoring function to  always count the full size of the piece you placed. I believe you can change `let result = count(diff(after, prev))` to `let result = count(placement)`.

**Comment by pmurman** [comment]
> let result = count(diff(after, prev)) to let result = count(placement)
Ran some tests, same outcome. I'll have to dig deeper into it.
